module.exports={
	database:{
		host:'127.0.0.1',
		port:'3306',
		user:'root',
		password:'pw',
		database:'chess'
	}
}
/*module.exports={
	database:{
	  host:'127.0.0.1',
	  port:'3306',
	  user:'spengerg',
	  password:'NietyephahynWoi',
	  database:'spengerg_chess',
	  socket:'/var/lib/mysql/mysql.sock',
	});
*/